testproj/accounts/urls.py
from django.conf.urls import url

from .views import (
    ProfileDetailView, ProfileUpdateView
)


urlpatterns = [
    url(r'^(?P<slug>[-\w]+)/$', ProfileDetailView.as_view(), name='profile_detail'),
    url(r'^(?P<slug>[-\w]+)/update/$', ProfileUpdateView.as_view(), name='profile_update'),
]

testproj/landing/urls.py
from django.conf.urls import url

from .views import (
    MainPageView
)

urlpatterns = [
    url(r'^$', MainPageView.as_view(), name='main_page'),
]

testproj/registration/urls.py
"""
Backwards-compatible URLconf for existing django-registration
installs; this allows the standard ``include('registration.urls')`` to
continue working, but that usage is deprecated and will be removed for
django-registration 1.0. For new installs, use
``include('registration.backends.default.urls')``.

"""

import warnings

warnings.warn("include('testproj.registration.urls') is deprecated; use include('testproj.registration.backends.default.urls') instead.",
              DeprecationWarning)

from .backends.default.urls import *  # NOQA

testproj/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^', include('testproj.landing.urls', namespace='landing')),
    url(r'^accounts/', include('testproj.accounts.urls', namespace='accounts')),
    url(r'^auth/', include('testproj.registration.backends.default.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testproj/accounts/models.py
from django.db import models
from django.conf import settings
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.core.urlresolvers import reverse
from django.db.models.signals import post_save
from django.utils.translation import ugettext_lazy as _

from slugify import UniqueSlugify
from imagekit.processors import Adjust, ResizeToFill
from imagekit.models import ProcessedImageField, ImageSpecField
from django_countries.fields import CountryField

from testproj.utils.model_utils import UploadToPathAndRename


class Profile(models.Model):
    SEX_CHOICES = (
        (1, _('man')),
        (0, _('woman')),
        (None, _("don't show"))
    )
    user = models.OneToOneField(User, related_name='profile')
    sex = models.IntegerField(choices=SEX_CHOICES, blank=True, null=True, verbose_name=_('gender'))
    slug = models.SlugField(unique=True, max_length=100, help_text=_("automatically generated, don't change manually !"))
    address_line1 = models.CharField(verbose_name=_("address line1"), max_length=200, blank=True, null=True)
    address_line2 = models.CharField(verbose_name=_("address line2"), max_length=200, blank=True, null=True)
    city = models.CharField(_("city"), max_length=200, blank=True, null=True)
    state = CountryField(blank=True, null=True, blank_label=_('(select country)'))
    postal = models.CharField(_("postal"), max_length=200, blank=True, null=True)
    dob = models.DateField(null=True, blank=True, verbose_name=_('birthday'))
    phone = models.CharField(
        max_length=50,
        verbose_name=_("phone"),
        blank=True,
        null=True,
    )
    cell = models.CharField(
        max_length=20,
        verbose_name=_("cell number"),
        blank=True,
        null=True,
        validators=[
            RegexValidator(
                regex=r'^\+?1?\d{9,15}$',
                message=_("Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
            )
        ]
    )
    profile_image = ProcessedImageField(upload_to=UploadToPathAndRename('profile_images'),
                                        processors=[
                                            ResizeToFill(400, 400),
                                            Adjust(sharpness=1.1, contrast=1.1)],
                                        format='JPEG',
                                        options={'quality': 90}, null=True, blank=True)

    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('accounts:profile_detail', kwargs={'slug': self.slug})

    # thumbnail for admin interface
    def admin_image_thumb(self):
        if self.profile_image:
            return '<img src="{0}{1}" width="100" height="100" />'.format(settings.MEDIA_URL, self.profile_image)
        else:
            return '<img src="{0}accounts/default/default-avatar.jpg" width="100" height="100" />'.format(settings.STATIC_URL)
    admin_image_thumb.allow_tags = True

    # small thumbnail and method for it
    profile_image_thumbnail_sm = ImageSpecField(
        source='profile_image',
        processors=[ResizeToFill(155, 155)],
        format='JPEG',
        options={'quality': 80}
    )

    def get_avatar_sm(self):
        if self.profile_image:
            return self.profile_image_thumbnail_sm.url
        else:
            return '{}accounts/default/default-avatar_sm.jpeg'.format(settings.STATIC_URL)

    # extra small thumbnail and method for it
    profile_image_thumbnail_xs = ImageSpecField(
        source='profile_image',
        processors=[ResizeToFill(48, 48)],
        format='JPEG',
        options={'quality': 80}
    )

    def get_avatar_xs(self):
        if self.profile_image:
            return self.profile_image_thumbnail_xs.url
        else:
            return '{}accounts/default/default-avatar_xs.jpeg'.format(settings.STATIC_URL)


def my_unique_check(text, uids):
    if text in uids:
        return False
    return not Profile.objects.filter(slug=text).exists()


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        slugify_unique = UniqueSlugify(
            unique_check=my_unique_check,
            separator='_',
            to_lower=True,
            max_length=100
        )
        slug = slugify_unique(instance.username)
        Profile.objects.create(user=instance, slug=slug)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

testproj/landing/models.py
from django.db import models

testproj/accounts/forms.py
from django import forms
from django.forms.models import model_to_dict, fields_for_model
from django.contrib.auth.models import User
from django_countries.widgets import CountrySelectWidget
from django.utils.translation import ugettext_lazy as _

from .models import Profile


class ProfileUpdateForm(forms.ModelForm):

    def __init__(self, instance=None, *args, **kwargs):
        _fields = ('first_name', 'last_name',)
        _initial = model_to_dict(instance.user, _fields) if instance is not None else {}
        kwargs.update(initial=_initial)
        super(ProfileUpdateForm, self).__init__(instance=instance, *args, **kwargs)
        self.fields.update(fields_for_model(User, _fields))

    class Meta(object):
        model = Profile

        fields = (
            'sex',
            'address_line1',
            'address_line2',
            'city',
            'state',
            'postal',
            'dob',
            'phone',
            'cell',
            'profile_image',
        )

        widgets = {
            'state': CountrySelectWidget(),
            'dob': forms.SelectDateWidget(
                years=list(reversed(range(1901, 2002))),
                empty_label=(_("Year"), _("Month"), _("Day")),
                attrs=({'style': 'width: 32%; display: inline-block;'})),
            'profile_image': forms.FileInput(),
            'sex': forms.RadioSelect(),
        }

    def save(self, *args, **kwargs):
        u = self.instance.user
        u.first_name = self.cleaned_data['first_name']
        u.last_name = self.cleaned_data['last_name']
        u.save()
        profile = super(ProfileUpdateForm, self).save(*args, **kwargs)
        return profile

testproj/landing/forms.py
from django import forms

testproj/accounts/views.py
from django.http import Http404
from django.conf import settings
from django.contrib import messages
from django.views.generic import DetailView
from django.views.generic.edit import UpdateView
from django.core.urlresolvers import reverse_lazy
from django.utils.translation import ugettext as _


from braces.views import LoginRequiredMixin

from .models import Profile
from .forms import ProfileUpdateForm


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'accounts/profile.html'

    def get_object(self):
        if not Profile.objects.filter(slug=self.kwargs['slug']).exists():
            raise Http404
        elif self.request.user.profile != Profile.objects.get(slug=self.kwargs['slug']) and not self.request.user.is_staff:
            raise Http404
        return self.get_queryset().get(slug=self.kwargs['slug'])


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'accounts/profile_update.html'
    form_class = ProfileUpdateForm

    def get_object(self):
        return self.request.user.profile

    def get_context_data(self, **kwargs):
        context = super(ProfileUpdateView, self).get_context_data(**kwargs)
        return context

    def get_success_url(self):
        messages.success(self.request, _('Profile updated successfully'))
        return reverse_lazy('accounts:profile_detail', kwargs={'slug': self.request.user.profile.slug})

testproj/landing/views.py
from django.conf import settings
from django.views.generic import TemplateView
from django.core.urlresolvers import reverse_lazy

from braces.views import LoginRequiredMixin


class MainPageView(LoginRequiredMixin, TemplateView):
    template_name = 'landing/main_page.html'

testproj/templates/accounts/profile.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load breadcrumbs %}


{% block title %}
    {{ block.super }} | {{ profile.user.get_full_name }}
{% endblock %}


{% block breadcrumb %}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-9">
        <h2>Profile</h2>
        <ol class="breadcrumb">
            <li class="">
                {% breadcrumb_url "Home" 'landing:main_page' %}
            </li>
            <li class="active">
               <strong>{{ request.user.get_full_name }}</strong>
            </li>
        </ol>
    </div>
</div>
{% endblock breadcrumb %}


{% block body %}
<div class="row m-b-lg m-t-lg">

    <div class="btn-group pull-right"><a class="btn btn-w-m btn-success" href="{% url 'accounts:profile_update' request.user.profile.slug %}" type="button">Edit <span class=""><i class="fa fa-cog"></i></span></a></div>

    <div class="col-md-2">
        <div class="">
            <img src="{{ profile.get_avatar_sm }}" class="img-circle circle-border m-b-md" alt="profile">
        </div>
    </div>

    <div class="col-md-6">

        <div class="ibox-content">
            <div class="">
                <div>
                    <h2 class="no-margins">
                        {{ profile.user.get_full_name }}
                    </h2>
                    <br>
                <address>
                    <strong>{{ profile.user.username|default_if_none:"-" }}</strong>
                    <br> {{ profile.address_line1|default_if_none:"-" }}
                    <br> {{ profile.address_line2|default_if_none:"-" }}
                    <br> {{ profile.city|default_if_none:"-" }}
                    <br> {{ profile.state.name|default_if_none:"-" }}
                    <br> {{ profile.postal|default_if_none:"-" }}
                    <br> {{ profile.dob|default_if_none:"-" }}
                    <br>
                    <abbr title="Phone">P:</abbr> {{ profile.phone|default_if_none:"-" }}
                    <br>
                    <abbr title="Cell Phone">Mobile:</abbr> {{ profile.cell|default_if_none:"-" }}
                </address>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock body %}

testproj/templates/accounts/profile_update.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load breadcrumbs %}
{% load widget_tweaks %}
{% load countries %}


{% block title %}
    {{ block.super }} | {{ profile.user.get_full_name }}
{% endblock %}

{% block breadcrumb %}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-9">
        <h2>Profile Update</h2>
        <ol class="breadcrumb">
            <li class="">
                {% breadcrumb_url "Home" 'landing:main_page' %}
            </li>
            <li class="">
                {% breadcrumb_url request.user.get_full_name 'accounts:profile_detail' request.user.profile.slug %}
            </li>
            <li class="active">
                <strong>Update</strong>
            </li>
        </ol>
    </div>
</div>
{% endblock breadcrumb %}


{% block body %}
<form method="POST" enctype="multipart/form-data" action="">{% csrf_token %}

    <div class="row m-b-lg m-t-lg">
        <div class="col-sm-2 col-md-3 col-md-offset-1 col-lg-2 col-lg-offset-2">
            <div class="form-group">
                <img alt="" id="image_avatar" class="img-thumbnail" src="{{ profile.get_avatar_sm }}">
                <span style="display:none">{{ form.profile_image }}</span>
            </div>
            <a id="browse" class="btn btn-block btn-warning fa fa-upload fa-lg"> {% trans 'UPLOAD' %}</a>
        </div>



        <div class="col-sm-10 col-md-8 col-lg-6 card-box">
            <div class="form-group">
                <span>{% trans 'Username' %}</span>
                <input type="text" class="form-control" id="id_username" maxlength="30" name="username" disabled placeholder="username" spellcheck="false" value="{{ profile.user.username|default_if_none:"" }}">
            </div>

            <div class="form-group">
                <span>{% trans 'Mail' %}</span>
                <input class="form-control" type="email" disabled id="id_email" maxlength="254" name="email" value="{{ profile.user.email|default_if_none:"" }}">
            </div>

            <div class="row">
                <div class="form-group col-sm-6">
                    <span>{% trans 'Name' %}</span>
                    {% render_field form.first_name class+="form-control" placeholder=form.first_name.label %}
                </div>

                <div class="form-group col-sm-6">
                    <span>{% trans 'Surname' %}</span>
                    {% render_field form.last_name class+="form-control" placeholder=form.last_name.label %}
                </div>
            </div>

                
            <div class="form-group">
                <label for="id_sex_0"><input {% if profile.sex == 1 %}checked="checked"{% endif %} id="id_sex_0" name="sex" type="radio" value="1"> {% trans 'Man' %}</label>
                <label for="id_sex_1"><input {% if profile.sex == 0 %}checked="checked"{% endif %} id="id_sex_1" name="sex" type="radio" value="0"> {% trans 'Woman' %}</label>
            </div>

            <div class="form-group">
                {{ form.birthday }}
            </div>


            <div class="form-group">
                {{ form.country }}
            </div>

            <div class="form-group">
                {% render_field form.address_line1 class+="form-control" placeholder=form.address_line1.label %}
            </div>

            <div class="form-group">
                {% render_field form.address_line2 class+="form-control" placeholder=form.address_line2.label %}
            </div>

            <div class="form-group">
                {% render_field form.phone class+="form-control" placeholder=form.phone.label %}
            </div>

            <div class="form-group">
                {% render_field form.cell class+="form-control" placeholder=form.cell.label %}
            </div>

            <div class="form-group">
                {% render_field form.city class+="form-control" placeholder=form.city.label %}
            </div>

            <div class="form-group">
                {% render_field form.state class+="form-control" placeholder=form.state.label %}
            </div>

            <div class="form-group">
                {% render_field form.postal class+="form-control" placeholder=form.postal.label %}
            </div>

            <div class="form-group">
                {% render_field form.dob class+="form-control" placeholder=form.dob.label %}
            </div>

            <div class="form-group">
                <button class="btn">{% trans 'SAVE' %}</button>
                <a href="{{ request.user.profile.get_absolute_url }}" class="btn btn-primary"> <span class="fa fa-arrow-left"></span>{% trans 'BACK' %}</a>
            </div>
        </div>

    </div>

</form>


{% endblock body %}



{% block page_script_base %}
{{ block.super }}
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <script type="text/javascript">
                toastr.warning("{{ error|escape }}")
            </script>
        {% endfor %}
    {% endfor %}
{% endif %}

<script type="text/javascript">
$('#browse').click(function(){
    $(this).parent().find('input').click();
});


document.getElementById("id_profile_image").onchange = function () {
    var reader = new FileReader();
    reader.onload = function (e) {
        // get loaded data and render thumbnail.
        document.getElementById("image_avatar").src = e.target.result;
    };

    // read the image file as a data URL.
    reader.readAsDataURL(this.files[0]);
};

</script>
{% endblock page_script_base %}